// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InvoicesColumns holds the columns for the "invoices" table.
	InvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "min_amount", Type: field.TypeString},
		{Name: "recipient", Type: field.TypeString},
		{Name: "beneficiary", Type: field.TypeString},
		{Name: "asset", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeString, Size: 256},
		{Name: "create_at", Type: field.TypeTime},
		{Name: "deadline", Type: field.TypeTime},
		{Name: "fill_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_checkout_at", Type: field.TypeTime, Nullable: true},
		{Name: "checkout_request_at", Type: field.TypeTime, Nullable: true},
		{Name: "cancel_at", Type: field.TypeTime, Nullable: true},
		{Name: "wallet_address", Type: field.TypeString, Unique: true},
		{Name: "encrypted_salt", Type: field.TypeBytes, Unique: true},
	}
	// InvoicesTable holds the schema information for the "invoices" table.
	InvoicesTable = &schema.Table{
		Name:       "invoices",
		Columns:    InvoicesColumns,
		PrimaryKey: []*schema.Column{InvoicesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InvoicesTable,
	}
)

func init() {
}
