// Code generated by ent, DO NOT EDIT.

package database

import (
	"context"
	"cpg/pkg/ent/database/invoice"
	"cpg/pkg/ent/database/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// InvoiceUpdate is the builder for updating Invoice entities.
type InvoiceUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceMutation
}

// Where appends a list predicates to the InvoiceUpdate builder.
func (iu *InvoiceUpdate) Where(ps ...predicate.Invoice) *InvoiceUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetFillAt sets the "fill_at" field.
func (iu *InvoiceUpdate) SetFillAt(t time.Time) *InvoiceUpdate {
	iu.mutation.SetFillAt(t)
	return iu
}

// SetNillableFillAt sets the "fill_at" field if the given value is not nil.
func (iu *InvoiceUpdate) SetNillableFillAt(t *time.Time) *InvoiceUpdate {
	if t != nil {
		iu.SetFillAt(*t)
	}
	return iu
}

// ClearFillAt clears the value of the "fill_at" field.
func (iu *InvoiceUpdate) ClearFillAt() *InvoiceUpdate {
	iu.mutation.ClearFillAt()
	return iu
}

// SetCancelAt sets the "cancel_at" field.
func (iu *InvoiceUpdate) SetCancelAt(t time.Time) *InvoiceUpdate {
	iu.mutation.SetCancelAt(t)
	return iu
}

// SetNillableCancelAt sets the "cancel_at" field if the given value is not nil.
func (iu *InvoiceUpdate) SetNillableCancelAt(t *time.Time) *InvoiceUpdate {
	if t != nil {
		iu.SetCancelAt(*t)
	}
	return iu
}

// ClearCancelAt clears the value of the "cancel_at" field.
func (iu *InvoiceUpdate) ClearCancelAt() *InvoiceUpdate {
	iu.mutation.ClearCancelAt()
	return iu
}

// SetLockExpireAt sets the "lock_expire_at" field.
func (iu *InvoiceUpdate) SetLockExpireAt(t time.Time) *InvoiceUpdate {
	iu.mutation.SetLockExpireAt(t)
	return iu
}

// SetNillableLockExpireAt sets the "lock_expire_at" field if the given value is not nil.
func (iu *InvoiceUpdate) SetNillableLockExpireAt(t *time.Time) *InvoiceUpdate {
	if t != nil {
		iu.SetLockExpireAt(*t)
	}
	return iu
}

// SetLockHolder sets the "lock_holder" field.
func (iu *InvoiceUpdate) SetLockHolder(u uuid.UUID) *InvoiceUpdate {
	iu.mutation.SetLockHolder(u)
	return iu
}

// SetNillableLockHolder sets the "lock_holder" field if the given value is not nil.
func (iu *InvoiceUpdate) SetNillableLockHolder(u *uuid.UUID) *InvoiceUpdate {
	if u != nil {
		iu.SetLockHolder(*u)
	}
	return iu
}

// Mutation returns the InvoiceMutation object of the builder.
func (iu *InvoiceUpdate) Mutation() *InvoiceMutation {
	return iu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *InvoiceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *InvoiceUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *InvoiceUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *InvoiceUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iu *InvoiceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoice.Table, invoice.Columns, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeString))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.FillAt(); ok {
		_spec.SetField(invoice.FieldFillAt, field.TypeTime, value)
	}
	if iu.mutation.FillAtCleared() {
		_spec.ClearField(invoice.FieldFillAt, field.TypeTime)
	}
	if value, ok := iu.mutation.CancelAt(); ok {
		_spec.SetField(invoice.FieldCancelAt, field.TypeTime, value)
	}
	if iu.mutation.CancelAtCleared() {
		_spec.ClearField(invoice.FieldCancelAt, field.TypeTime)
	}
	if value, ok := iu.mutation.LockExpireAt(); ok {
		_spec.SetField(invoice.FieldLockExpireAt, field.TypeTime, value)
	}
	if value, ok := iu.mutation.LockHolder(); ok {
		_spec.SetField(invoice.FieldLockHolder, field.TypeUUID, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// InvoiceUpdateOne is the builder for updating a single Invoice entity.
type InvoiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceMutation
}

// SetFillAt sets the "fill_at" field.
func (iuo *InvoiceUpdateOne) SetFillAt(t time.Time) *InvoiceUpdateOne {
	iuo.mutation.SetFillAt(t)
	return iuo
}

// SetNillableFillAt sets the "fill_at" field if the given value is not nil.
func (iuo *InvoiceUpdateOne) SetNillableFillAt(t *time.Time) *InvoiceUpdateOne {
	if t != nil {
		iuo.SetFillAt(*t)
	}
	return iuo
}

// ClearFillAt clears the value of the "fill_at" field.
func (iuo *InvoiceUpdateOne) ClearFillAt() *InvoiceUpdateOne {
	iuo.mutation.ClearFillAt()
	return iuo
}

// SetCancelAt sets the "cancel_at" field.
func (iuo *InvoiceUpdateOne) SetCancelAt(t time.Time) *InvoiceUpdateOne {
	iuo.mutation.SetCancelAt(t)
	return iuo
}

// SetNillableCancelAt sets the "cancel_at" field if the given value is not nil.
func (iuo *InvoiceUpdateOne) SetNillableCancelAt(t *time.Time) *InvoiceUpdateOne {
	if t != nil {
		iuo.SetCancelAt(*t)
	}
	return iuo
}

// ClearCancelAt clears the value of the "cancel_at" field.
func (iuo *InvoiceUpdateOne) ClearCancelAt() *InvoiceUpdateOne {
	iuo.mutation.ClearCancelAt()
	return iuo
}

// SetLockExpireAt sets the "lock_expire_at" field.
func (iuo *InvoiceUpdateOne) SetLockExpireAt(t time.Time) *InvoiceUpdateOne {
	iuo.mutation.SetLockExpireAt(t)
	return iuo
}

// SetNillableLockExpireAt sets the "lock_expire_at" field if the given value is not nil.
func (iuo *InvoiceUpdateOne) SetNillableLockExpireAt(t *time.Time) *InvoiceUpdateOne {
	if t != nil {
		iuo.SetLockExpireAt(*t)
	}
	return iuo
}

// SetLockHolder sets the "lock_holder" field.
func (iuo *InvoiceUpdateOne) SetLockHolder(u uuid.UUID) *InvoiceUpdateOne {
	iuo.mutation.SetLockHolder(u)
	return iuo
}

// SetNillableLockHolder sets the "lock_holder" field if the given value is not nil.
func (iuo *InvoiceUpdateOne) SetNillableLockHolder(u *uuid.UUID) *InvoiceUpdateOne {
	if u != nil {
		iuo.SetLockHolder(*u)
	}
	return iuo
}

// Mutation returns the InvoiceMutation object of the builder.
func (iuo *InvoiceUpdateOne) Mutation() *InvoiceMutation {
	return iuo.mutation
}

// Where appends a list predicates to the InvoiceUpdate builder.
func (iuo *InvoiceUpdateOne) Where(ps ...predicate.Invoice) *InvoiceUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *InvoiceUpdateOne) Select(field string, fields ...string) *InvoiceUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Invoice entity.
func (iuo *InvoiceUpdateOne) Save(ctx context.Context) (*Invoice, error) {
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *InvoiceUpdateOne) SaveX(ctx context.Context) *Invoice {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *InvoiceUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *InvoiceUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iuo *InvoiceUpdateOne) sqlSave(ctx context.Context) (_node *Invoice, err error) {
	_spec := sqlgraph.NewUpdateSpec(invoice.Table, invoice.Columns, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeString))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`database: missing "Invoice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoice.FieldID)
		for _, f := range fields {
			if !invoice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("database: invalid field %q for query", f)}
			}
			if f != invoice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.FillAt(); ok {
		_spec.SetField(invoice.FieldFillAt, field.TypeTime, value)
	}
	if iuo.mutation.FillAtCleared() {
		_spec.ClearField(invoice.FieldFillAt, field.TypeTime)
	}
	if value, ok := iuo.mutation.CancelAt(); ok {
		_spec.SetField(invoice.FieldCancelAt, field.TypeTime, value)
	}
	if iuo.mutation.CancelAtCleared() {
		_spec.ClearField(invoice.FieldCancelAt, field.TypeTime)
	}
	if value, ok := iuo.mutation.LockExpireAt(); ok {
		_spec.SetField(invoice.FieldLockExpireAt, field.TypeTime, value)
	}
	if value, ok := iuo.mutation.LockHolder(); ok {
		_spec.SetField(invoice.FieldLockHolder, field.TypeUUID, value)
	}
	_node = &Invoice{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
