// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// InvoiceOrErr calls the predicate only if the error is not nit.
func InvoiceOrErr(p Invoice, err error) Invoice {
	return func(s *sql.Selector) {
		if err != nil {
			s.AddError(err)
			return
		}
		p(s)
	}
}
